name: taglow_admin
description: Taglow admin operations console.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/taglow_logo.svg
