name: taglow_admin
description: Taglow admin operations console.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.3
  go_router: ^14.8.1
  cupertino_icons: ^1.0.9
  crypto: ^3.0.7
  image_picker: ^1.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo/taglow_logo.png
